### ISSUE TITLE
Comparison with NMSLib (HNSW)

### ISSUE THREAD

**Issue by Neltherion** [teemupitkanen/mrpt#12]
Could you please give us a comparison with [NMSLib (HNSW Algorithm)](https://github.com/nmslib/nmslib) ?

**Comment by MilesCranmer** [comment]
It looks like it's included on https://github.com/erikbern/ann-benchmarks with the Euclidean metrics

**Comment by vioshyvo** [comment]
Yes, it is on the ANN benchmarks, but the results are bad because the parameters tested are suboptimal (maximum number of trees used is 100, but optimal number of trees is higher for almost all the data sets and recall levels we have tested, usually somewhere between 100 - 1500). 

We are actually currently working on automatic tuning algorithm for MRPT, and when it is finished, we will make a pull request to ANN benchmarks with proper parameter values.

**Comment by vioshyvo** [comment]
Now we have updated proper parameters (and automatic hyperparameter tuning) to ann-benchmarks, so the results should be better next time they run the comparisons. 

The comparisons to HNSW (FAISS version) and IVFPQ from FAISS are also actually included in our new article ([arxiv preprint](https://arxiv.org/abs/1812.07484)) (to appear in PAKDD 2019): on the compared data sets MRPT is slower than HNSW (we are working on that one, stay tuned...),  but faster than IVFPQ.
