### ISSUE TITLE
Problem with non-autotuned indices

### ISSUE THREAD

**Issue by rhiestan** [teemupitkanen/mrpt#13]
First of all, I would like to thank the authors of this library for their great work! In my tests mrpt is faster than FLANN and many other libraries.
I have a question regarding non-autotuned indices. I am using mrpt in my program Regard3D (a tool for structure from motion) for finding matches of LIOP image descriptors (144 floats).
First I tried with creating autotuned indices, which works perfect. However, creating the indices is slower, so I tried to use the parameters found in autotuning, and to create non-autotuned indices. And for some examples this works fine, while for others I receive sometimes -1 in the query result.
I should mention that Regard3D always searches 2 nearest neighbours, to determine "good" from "bad" matches. A "good" match is one where the second-best distance is x times larger than the best one, x being configurable by the user.
In my tests, I used the parameters found in autotuning for one image (set of keypoint descriptors) for many different  images and different amount of samples. Is this allowed by the library? How should one go about creating a non-autotuned index and then successfully create indices for other samples and then query 2 nearest neighbours?
Of course the obvious work-around is to discard the results with -1, but is there a better way?

**Comment by vioshyvo** [comment]
Great to hear you find it useful! While you can surely use the parameters tuned for one data set to build indices for other data sets, as you suspected, there is no guarantee that they are optimal or even any good, especially if the sample sizes or dimensions of the data sets are very different. What is the scale of the sample sizes of your data sets, this may be why the same parameters are not working for them? 

Another problem may be the vote threshold: there are 3 parameters autotuning tunes: number and depth of trees, and vote threshold. The number and depth of trees and depth are parameters of the index, but vote threshold is a parameter of the query (you can query the same index using different vote thresholds). So when using the parameters found by autotuning to build a not-autotuned index, also the optimal vote count has to be passed to `query()`, like this (if you use a different vote threshold, there is again not any guarantee that the results are good):

```c++
int k = 2;
double target_recall = 0.9;
Mrpt mrpt_autotuned(X);
mrpt_autotuned.grow(target_recall, Q, k);
Mrpt_Parameters par = mrpt_autotuned.parameters();

Mrpt mrpt_not_autotuned(X);
mrpt_not_autotuned.grow(par.n_trees, par.depth);

std::vector<int> res(k);
mrpt_not_autotuned.query(Q.col(0), k, par.votes, &res[0]);

```

But if you just want faster index building times, I guess the easiest solution would be to use autotuning, and just lower its argument `trees_max` from its default (which is a square root of the sample size of data). For example, if you observe that for your data sets the optimal parameters for your chosen recall level have usually less than 50 trees, just set `trees_max = 50`. 

This should reduce the autotuning time, since in our experience most of the autotuning overhead compared to normal index building is because it grows more trees, and then estimates the optimal amount of trees to use.

Another way to reduce the autotuning time is to use a smaller set of test queries: in our experience 100 test queries is enough to find near-optimal parameters. Actually we just released a version of autotuning (function `grow_autotune`) which samples a test set (100 points as default) of query points from the data set, so no separate set of test query points is even required anymore for autotuning (the minimal example in README is now updated to use this version of autotuning function).

**Comment by rhiestan** [comment]
Thanks a lot for your hints! I will try out the new autotuning and setting trees_max.
However, my code worked exactly like you describe, I also set votes. Nevertheless I sometimes received -1. Of course the number of samples varies a lot, maybe some combinations of parameters and number of samples result in -1.

**Comment by vioshyvo** [comment]
Let us know how it goes! Anyways, it is possible to get -1 results sometimes even with good parameters, so the only way to completely avoid them is to guard against them as you suggested. A quick fix in this case would to repeat the query with a lower vote threshold, since -1 results mean that the candidate set size is less than k (2 in your case). Actually one early version of the library did exactly this inside the query function, so it could not return -1.
