### ISSUE TITLE
Searching for nearest neighbors in parallel

### ISSUE THREAD

**Issue by jeroenvuurens** [teemupitkanen/mrpt#3]
Wonderful work! I am calling MRPT from python. Is it possible to support NN finding in parallel for a set of queries?

**Comment by ryanrhymes** [comment]
probably not in the current mrpt as far as i can tell. but since query only needs to read model, it should be very easy to spawn multiple threads in Python to perform the query. one thing to be careful is that threads are concurrent but not parallel in Python (thanks to GIL), so actual performance improvement is not clear given mrpt itself is already very fast ... :)

**Comment by jeroenvuurens** [comment]
Thank you for your response. Multithreading/multiprocessing might be faster though if the GIL is released, the underlying algorithm is C anyway. A neat way would be for these processes to share the index. I'm not sure how the exact search is implemented, but working on a 32 core machine, exact search is actually about twice as fast for me than the most optimal MRPT settings that give a 1.0 accuracy on a sample of 1000 points.
